In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

/home/sunbeam/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
df = pd.read_csv("../Churn_Modelling.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.isna().values.any()

False

In [5]:
import pandas_profiling

/home/sunbeam/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sunbeam/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sunbeam/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/home/sunbeam/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [6]:
#pandas_profiling.ProfileReport(df)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
#from sklearn.preprocessing import StandardScaler
#from sklearn.preprocessing import MinMaxScaler

In [10]:
#stdscaler = StandardScaler()
#minscaler = MinMaxScaler()

In [11]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [12]:
df.drop(labels=['CustomerId','RowNumber','Surname'],axis=1,inplace=True)

In [13]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [14]:
df['Gender']  = pd.get_dummies(df['Gender'],drop_first=True)

In [15]:
df2 = pd.get_dummies(data =df,columns=['Geography'])

In [16]:
df2.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1                 1   
1               1        112542.58       0                 0   
2               0        113931.57       1                 1   
3               0         93826.63       0                 1   
4               1         79084.10       0                 0   

   Geography_Germany  Geography_Spain  
0                  0                0  
1                  0                1  
2                  0                0  
3                  0                0  
4                  0                1

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

/home/sunbeam/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sunbeam/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sunbeam/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [18]:
tree = DecisionTreeClassifier()
forest = RandomForestClassifier()

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X = df2.drop('Exited',axis='columns')
y = df2['Exited']

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25)

In [22]:
model_tree = tree.fit(X_train,y_train)
model_forest = forest.fit(X_train,y_train)

In [23]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report

In [24]:
y_pred_tree = model_tree.predict(X_test)

In [25]:
y_pred_forest = model_forest.predict(X_test)

In [26]:
accuracy_score(y_test,y_pred_tree)

0.7832

In [27]:
accuracy_score(y_test,y_pred_forest)

0.8608

In [28]:
# for Decision Tree
confusion_matrix(y_test,y_pred_tree)

array([[1720,  284],
       [ 258,  238]])

In [29]:
# For random Forest
confusion_matrix(y_test,y_pred_forest)

array([[1927,   77],
       [ 271,  225]])

In [31]:
print(classification_report(y_test,y_pred_forest))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      2004
           1       0.75      0.45      0.56       496

    accuracy                           0.86      2500
   macro avg       0.81      0.71      0.74      2500
weighted avg       0.85      0.86      0.85      2500



In [ ]:
# as F1 Score is very low for Class 1 that is happening becauese of class is imbanaced 


In [ ]:
# FixinG the Class Imbalanced promblem

In [42]:
df0_class = df2[df2['Exited']== 0]
df1_class = df2[df2['Exited'] == 1]

In [46]:
df0_class.shape

(7963, 13)

In [44]:
df1_class.shape

(2037, 13)

In [47]:
df2.Exited.value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [64]:
count_class_0,class_count_1 = df2.Exited.value_counts()

In [69]:
# Random Under Sampling
df_class_0_under = df0_class.sample(class_count_1)

In [70]:
df_class_0_under.shape

(2037, 13)

In [71]:
df_under_sampling = pd.concat([df_class_0_under,df1_class],axis=0)

In [72]:
df_under_sampling["Exited"].value_counts()

1    2037
0    2037
Name: Exited, dtype: int64

In [73]:
df_under_sampling.head()

CreditScore  Gender  Age  Tenure   Balance  NumOfProducts  HasCrCard  \
9419          686       1   26       1  57422.62              1          1   
7751          750       0   39       6      0.00              2          0   
7470          850       0   47       4  99219.47              2          1   
5474          651       0   34       9      0.00              2          1   
4144          655       1   44       8  87471.63              1          0   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
9419               1         79189.40       0                 0   
7751               0         19264.33       0                 0   
7470               1        122141.13       0                 0   
5474               0        138113.71       0                 1   
4144               1        188593.98       0                 1   

      Geography_Germany  Geography_Spain  
9419                  1                0  
7751                  0                1  
7470                  1                0  
5474                  0                0  
4144                  0                0

In [74]:
def split_data(df):
    X = df.drop('Exited',axis='columns')
    y = df['Exited']
    return X,y

    

In [79]:
X1,y1 =split_data(df_under_sampling)

In [144]:
def tts(X,y):
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20,stratify = y)
    return X_train,X_test,y_train,y_test

In [82]:
X_train,X_test,y_train,y_test = tts(X1,y1)

In [85]:
model_forest_under = forest.fit(X_train,y_train)

In [87]:
y_pred_forest_under = model_forest_under.predict(X_test)

In [88]:
accuracy_score(y_test,y_pred_forest_under)

0.7865030674846626

In [89]:
confusion_matrix(y_test,y_pred_forest_under)

array([[332,  82],
       [ 92, 309]])

In [91]:
print(classification_report(y_test,y_pred_forest_under))

              precision    recall  f1-score   support

           0       0.78      0.80      0.79       414
           1       0.79      0.77      0.78       401

    accuracy                           0.79       815
   macro avg       0.79      0.79      0.79       815
weighted avg       0.79      0.79      0.79       815



# OverSampling

In [127]:
df_class1_over = df1_class.sample(count_class_0,replace=True)

In [131]:
df_test_over = pd.concat([df0_class,df_class1_over],axis = 0)

In [132]:
df_test_over['Exited'].value_counts()

1    7963
0    7963
Name: Exited, dtype: int64

In [134]:
X,y = split_data(df_test_over)

In [145]:
X_train,X_test,y_train,y_test = tts(X,y)

In [146]:
model_foresr_over = forest.fit(X_train,y_train)

In [147]:
y_true_over = model_foresr_over.predict(X_test)

In [149]:
print(classification_report(y_test,y_true_over))

              precision    recall  f1-score   support

           0       0.96      0.93      0.94      1593
           1       0.93      0.97      0.95      1593

    accuracy                           0.95      3186
   macro avg       0.95      0.95      0.95      3186
weighted avg       0.95      0.95      0.95      3186

